from hadoop_optimizer.drl_telemetry.consts.telemetry_types import DRLTelemetryType

# TODO: CONSIDER USING MEMORY DIFFS AS ANOTHER FEATURE
FIELD_NAMES_TO_AVERAGE = [DRLTelemetryType.SYSTEM_MEMORY_PERCENT]
FIELD_NAMES_TO_SUM = [
    # raw fields
    DRLTelemetryType.SYSTEM_DISK_READ_COUNT,
    DRLTelemetryType.SYSTEM_DISK_WRITE_COUNT,
    DRLTelemetryType.SYSTEM_DISK_READ_KB,
    DRLTelemetryType.SYSTEM_DISK_WRITE_KB,
    DRLTelemetryType.SYSTEM_DISK_READ_TIME,
    DRLTelemetryType.SYSTEM_DISK_WRITE_TIME,
    DRLTelemetryType.SYSTEM_PACKETS_SENT,
    DRLTelemetryType.SYSTEM_PACKETS_RECEIVED,
    DRLTelemetryType.SYSTEM_NETWORK_SENT_KB,
    DRLTelemetryType.SYSTEM_NETWORK_RECEIVED_KB,

    # Aggregations
    # TODO: CONSIDER REPRESENTING RESOURCES' ENERGY CONSUMPTION AS A FRACTION OF THE TOTAL CONSUMPTION
    #  (INSTEAD OF AS ABSOLUTE NUMBERS)
    DRLTelemetryType.SYSTEM_CPU_INTEGRAL,
    DRLTelemetryType.SYSTEM_TOTAL_ENERGY_MWH,
    DRLTelemetryType.SYSTEM_CPU_ENERGY_MWH,
    DRLTelemetryType.SYSTEM_RAM_ENERGY_MWH,
    DRLTelemetryType.SYSTEM_DISK_READ_ENERGY_MWH,
    DRLTelemetryType.SYSTEM_DISK_WRITE_ENERGY_MWH,
    DRLTelemetryType.SYSTEM_NETWORK_RECEIVED_ENERGY_MWH,
    DRLTelemetryType.SYSTEM_NETWORK_SENT_ENERGY_MWH
]
