# logtypes=[('wineventlog:security', '10'),
#           ('wineventlog:security', '2004'),
#           ('xmlwineventlog:microsoft-windows-sysmon/operational', '16'),
#           ('wineventlog:security', '1'),
#           ('xmlwineventlog:microsoft-windows-sysmon/operational', '13'),
#           ('xmlwineventlog:microsoft-windows-sysmon/operational', '389'),
#           ('wineventlog:security', '4'), ('wineventlog:security', '1000'),
#           ('wineventlog:security', '7040'),
#           ('xmlwineventlog:microsoft-windows-sysmon/operational', '80'),
#           ('xmlwineventlog:microsoft-windows-sysmon/operational', '11'),
#           ('wineventlog:security', '4657'),
#           ('xmlwineventlog:microsoft-windows-sysmon/operational', '0'),
#           ('wineventlog:application', '1002'),
#           ('wineventlog:security', '5'),
#           ('wineventlog:security', '2005'),
#           ('wineventlog:security', '6'),
#           ('wineventlog:system', '7040'),
#           ('wineventlog:system', '7045'),  
#           ('wineventlog:system', '6008'),
#           ('wineventlog:system', '1074'),
#           ('xmlwineventlog:microsoft-windows-sysmon/operational', '3269'),
#           ('xmlwineventlog:microsoft-windows-sysmon/operational', '2'),
#           ('xmlwineventlog:microsoft-windows-sysmon/operational', '8'),
#           ('wineventlog:security', '4756'),
#           ('wineventlog:application', '40'),
#           ('wineventlog:security', '4740'),
#           ('xmlwineventlog:microsoft-windows-sysmon/operational', '636'), 
#           ('wineventlog:security', '5140'),
#           ('wineventlog:security', '4688'),
#           ('wineventlog:security', '0'),
#           ('wineventlog:security', '4625'),
#           ('wineventlog:security', '7045'),
#           ('xmlwineventlog:microsoft-windows-sysmon/operational', '3268'),
#           ('wineventlog:application', '1000'),
#           ('wineventlog:application', '1'),
#           ('xmlwineventlog:microsoft-windows-sysmon/operational', '17'),
#           ('wineventlog:application', '4'),
#           ('xmlwineventlog:microsoft-windows-sysmon/operational', '14'),
#           ('wineventlog:security', '2'),
#           ('wineventlog:security', '4720'),
#           ('xmlwineventlog:microsoft-windows-sysmon/operational', '12'),
#           ('xmlwineventlog:microsoft-windows-sysmon/operational', '40'),
#           ('wineventlog:security', '4732'),
#           ('xmlwineventlog:microsoft-windows-sysmon/operational', '443'),
#           ('xmlwineventlog:microsoft-windows-sysmon/operational', '3'),
#           ('xmlwineventlog:microsoft-windows-sysmon/operational', '10'),
#           ('wineventlog:security', '4728'),
#           ('wineventlog:application', '1074'),
#           ('wineventlog:security', '4624'),
#           ('wineventlog:security', '4634'),
#           ('xmlwineventlog:microsoft-windows-sysmon/operational', '1'),
#           ('wineventlog:application', '6008'),
#           ('xmlwineventlog:microsoft-windows-sysmon/operational', '4'), 
#           ('wineventlog:security', '4663'),
#           ('wineventlog:application', '0'),
#           ('wineventlog:security', '4675'),
#           ('xmlwineventlog:microsoft-windows-sysmon/operational', '5'),
#           ('wineventlog:security', '40'),
#           ('wineventlog:security', '601'), 
#           ('wineventlog:security', '520'),
#           ('wineventlog:security', '3')]
logtypes=[('xmlwineventlog:microsoft-windows-sysmon/operational', '8'),
 ('wineventlog:security', '2005'),
 ('wineventlog:security', '4624'),
 ('wineventlog:security', '4756'),
 ('xmlwineventlog:microsoft-windows-sysmon/operational', '3'),
 ('xmlwineventlog:microsoft-windows-sysmon/operational', '14'),
 ('wineventlog:security', '1102'),
 ('wineventlog:system', '1074'),
 ('xmlwineventlog:microsoft-windows-sysmon/operational', '13'),
 ('wineventlog:system', '7040'),
 ('wineventlog:system', '6008'),
 ('wineventlog:security', '2004'),
 ('wineventlog:security', '5140'),
 ('wineventlog:application', '1000'),
 ('xmlwineventlog:microsoft-windows-sysmon/operational', '12'),
 ('wineventlog:security', '4688'),
 ('wineventlog:security', '4657'),
 ('wineventlog:security', '7045'),
 ('wineventlog:security', '4728'),
 ('wineventlog:security', '1100'),
 ('xmlwineventlog:microsoft-windows-sysmon/operational', '11'),
 ('wineventlog:security', '4634'),
 ('wineventlog:security', '4663'),
 ('wineventlog:system', '104'),
 ('wineventlog:security', '4720'),
 ('wineventlog:security', '4625'),
 ('wineventlog:security', '4732'),
 ('xmlwineventlog:microsoft-windows-sysmon/operational', '16')]